### ISSUE TITLE
Feature request: allow choosing layouts independently from pin system

### ISSUE THREAD

**Issue by killianhuyghe** [videosdk-live/videosdk-rtc-react-prebuilt-ui#15]
Having these layout options (without pinning anyone) would be great:
```
- layout: GRID, SPOTLIGHT or SIDEBAR, with main speaker(s) based on mic activity.
- canChangeLayout: boolean
```

If pinning is allowed, pinning someone would move to the pin layout, allowing a different layout when there are pinned participants or not.

**Comment by arjun-kava** [comment]
Hey, @killianhuyghe.  this is on a roadmap, will take it soon. Thanks for raising it.

**Comment by arjun-kava** [comment]
It is launched in 3.x version
