### ISSUE TITLE
Unable to upload recordings in AWS S3

### ISSUE THREAD

**Issue by alokscra26032011Zk** [videosdk-live/videosdk-rtc-react-prebuilt-ui#31]
recording: {
    autoStart: true, // auto start recording on participant joined
    enabled: true,
    webhookUrl: "https://www.videosdk.live/callback",
    awsDirPath: `/meeting-recordings/${meetingId}/`, // automatically save recording in this s3 path
  },

I'm unable to upload recorded video to our s3 bucket...Can you help with the same ?

**Comment by ChintanRajpara** [comment]
hey, you have to configure your s3 bucket configuration as per the api keys  

you can add this in our User Dashboard [app.videosdk.live](https://app.videosdk.live/api-keys)
