### ISSUE TITLE
token issues 

### ISSUE THREAD

**Issue by muhammad-jiku** [videosdk-live/videosdk-rtc-react-prebuilt-ui#51]
I built a video chat app about a week ago by using videoSDK token, but yesterday, the token was expired and the whole site crashed!! then I had to use another token to activate the site again!! My question is if it happens randomly, it would be so difficult to maintain the site! is there any solution available for this problem?

**Comment by rajansurani** [comment]
@muhammad-jiku You have to setup an Auth API Server from where you can generate token whenever a meeting is initialized. Having a static token is not the best practice as it can be misused.

Here is the example for setting up an Auth API Server which will have an API endpoint to generate the token.
https://github.com/videosdk-live/videosdk-rtc-api-server-examples/tree/main/nodejs
